# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

rule_files:
  - "prometheus_contact_book_alerts.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "localhost:9093" # Add your Alertmanager address here.

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "contact-book"

    static_configs:
      - targets: ["localhost:8083"] # Add your contact book service address here.


